### PR TITLE
Fixes #53: don't fuse blend-only connectors

### LINKED ISSUE #53: Assert violation to_buf_aux_: start_pos >= curr_pos
This fails: 

```ocaml
    let to_buf_aux_ ?(indent = 0) (out : O.t) start_pos p curr_pos =
      assert (Pos.compare curr_pos start_pos <= 0);
```

Apologies no hints to reproduce, isolating this is on the way to fixing it, I need to fix this anyway...
Slightly more likely that I'm violating some invariant than that there's a bug, but both cases need fixing -- we cannot cryptically fail on a non-contrived user mistake.

### PR DESCRIPTION
**Pull request by lukstafi**
See updated blending test.

### CODE REVIEW

**Comment by c-cube** [comment]
That looks simpler somehow, and the tests pass, let's go!

File: src/printbox-text/PrintBox_text.ml [hunk 1]
```diff
@@ -335,75 +336,57 @@ end = struct
...
-    match
-      conn_basic.left, conn_basic.right, conn_basic.top, conn_basic.bottom
-    with
-    | false, false, false, false -> false
-    | true, false, false, false -> false
-    | false, true, false, false -> false
-    | false, false, true, false -> false
-    | false, false, false, true -> false
-    | _, _, _, _ -> true
+    (conn_basic.left || conn_basic.right || conn_basic.top || conn_basic.bottom)
```
Comment (lukstafi) [inline src/printbox-text/PrintBox_text.ml:365]: Ah this part is redundant, I forgot about it after changing the meaning of `blend_only` to include the empty case.
